title: "MedCom Messaging Profiles in FHIR"
description: "This page includes content about MedCom Messaging profiles"
logo: medcom+fhir-logo.png
description: "MedCom standard based on HL7 FHIR"
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
version: "Version 1.0.0-alpha.1"
fhir_version: "FHIR®© R4"
releasenote: /assets/documents/ReleaseNote-ENG.md
thisurl: https://medcomdk.github.io/MedCom-FHIR-Communication/
menuurl_item1: https://medcomdk.github.io/MedComLandingPage/
menutxt_item1: MedCom FHIR®© LandingPage