title: "MedCom Messaging Profiles in FHIR"
description: "This page includes content about MedCom Messaging profiles"
logo: medcom+fhir-logo.png
description: "MedCom standard based on HL7 FHIR"
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal